src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Repository\BlogRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BlogRepository::class)
 */
class Blog
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $short_content;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\ManyToMany(targetEntity=Tag::class, inversedBy="blogs")
     */
    private $blog_has_tag;

    /**
     * @ORM\ManyToMany(targetEntity=Sources::class, inversedBy="blogs")
     */
    private $blog_has_sources;

    public function __construct()
    {
        $this->setCreatedAt(new \DateTime());
        $this->blog_has_tag = new ArrayCollection();
        $this->blog_has_sources = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getShortContent(): ?string
    {
        return $this->short_content;
    }

    public function setShortContent(string $short_content): self
    {
        $this->short_content = $short_content;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection|tag[]
     */
    public function getBlogHasTag(): Collection
    {
        return $this->blog_has_tag;
    }

    public function addBlogHasTag(tag $blogHasTag): self
    {
        if (!$this->blog_has_tag->contains($blogHasTag)) {
            $this->blog_has_tag[] = $blogHasTag;
        }

        return $this;
    }

    public function removeBlogHasTag(tag $blogHasTag): self
    {
        if ($this->blog_has_tag->contains($blogHasTag)) {
            $this->blog_has_tag->removeElement($blogHasTag);
        }

        return $this;
    }

    /**
     * @return Collection|sources[]
     */
    public function getBlogHasSources(): Collection
    {
        return $this->blog_has_sources;
    }

    public function addBlogHasSource(sources $blogHasSource): self
    {
        if (!$this->blog_has_sources->contains($blogHasSource)) {
            $this->blog_has_sources[] = $blogHasSource;
        }

        return $this;
    }

    public function removeBlogHasSource(sources $blogHasSource): self
    {
        if ($this->blog_has_sources->contains($blogHasSource)) {
            $this->blog_has_sources->removeElement($blogHasSource);
        }

        return $this;
    }
}

src/Form/BlogType.php
<?php

namespace App\Form;

use App\Entity\Blog;
use App\Entity\Tag;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class BlogType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('short_content')
            ->add('content')
            // ->add('createdAt')
            // ->add('blog_has_tag', EntityType::class, [
            //     'class' => Tag::class,
            //     'multiple' => true,
            //     'choice_label' => 'name'
            // ])
            ->add('blog_has_tag', EntityType::class, [
                'class' => Tag::class,
                'choice_label' => 'name',
                'multiple' => true,
                'expanded' => true,
                // 'choices' => 'blog_has_tag'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Blog::class,
        ]);
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Blog;
use App\Entity\Tag;
use App\Form\BlogType;
use App\Repository\BlogRepository;
use App\Repository\TagRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/blog")
 */
class BlogController extends AbstractController
{
    /**
     * @Route("/", name="blog_index", methods={"GET"})
     */
    public function index(BlogRepository $blogRepository, TagRepository $tagRepository): Response
    {
        
        return $this->render('blog/index.html.twig', [
            'blogs' => $blogRepository->findAll(),
            'tags'  => $tagRepository->findAll()
        ]);
    }


    /**
     * @IsGranted("ROLE_ADMIN")
     * @Route("/new", name="blog_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $blog = new Blog();
        $form = $this->createForm(BlogType::class, $blog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($blog);
            $entityManager->flush();

            return $this->redirectToRoute('blog_index');
        }

        return $this->render('blog/new.html.twig', [
            'blog' => $blog,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="blog_show", methods={"GET"})
     */
    public function show(Blog $blog): Response
    {
        return $this->render('blog/show.html.twig', [
            'blog' => $blog,
        ]);
    }

    /**
     * @IsGranted("ROLE_ADMIN")
     * @Route("/{id}/edit", name="blog_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Blog $blog): Response
    {
        $form = $this->createForm(BlogType::class, $blog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('blog_index');
        }

        return $this->render('blog/edit.html.twig', [
            'blog' => $blog,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @IsGranted("ROLE_ADMIN")
     * @Route("/{id}", name="blog_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Blog $blog): Response
    {
        if ($this->isCsrfTokenValid('delete' . $blog->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($blog);
            $entityManager->flush();
        }

        return $this->redirectToRoute('blog_index');
    }
}

templates/blog/_delete_form.html.twig
<form method="post" action="{{ path('blog_delete', {'id': blog.id}) }}" onsubmit="return confirm('Êtes-vous certain de vouloir supprimer cette entrée?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ blog.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/blog/_form.html.twig
{{ form_start(form) }}

<div class="col">
	{{ form_row(form.title, {'name':'Titre'})}}
</div>

<div class="col">
	{{ form_row(form.short_content, {'name':'Version courte'})}}
</div>

<div class="col">
	{{ form_row(form.content, {'id':'summernote', 'name':'Contenu'})}}
</div>

{# <div class="col">
	{{ form_row(form.createdAt, {'name':'Date d\'ajout'})}}
</div> #}

<div class="col">
	{{ form_row(form.blog_has_tag, {'name':'Tag' })}}
</div>

{# {{ form_widget(form) }} #}
<button class="btn">{{ button_label|default('Créer') }}</button>
{{ form_end(form) }}

templates/blog/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer Blog{% endblock %}

{% block body %}
    <h1>Edit Blog</h1>

    {{ include('blog/_form.html.twig', {'button_label': 'Mettre à jour'}) }}

    <a href="{{ path('blog_index') }}">Retour à la liste</a>

    {{ include('blog/_delete_form.html.twig') }}
{% endblock %}

{% block css %}

<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.16/dist/summernote-bs4.min.css" rel="stylesheet">

{% endblock %}

{% block javascript %}

	<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.16/dist/summernote-bs4.min.js"></script>
	<script>
		$(document).ready(function () {
            $('#summernote').summernote();
        });
    </script>
    
{% endblock %}

templates/blog/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Index du blog
{% endblock %}

{% block body %}

	<h3 class="pt-5">Nos derniers articles :</h3>
	<div class="filter-button-group">
		<button type"button" class="btn btn-secondary element-item" data-filter="*">Tous les articles</button>
		{% for tag in tags %}
			<button type"button" class="btn btn-secondary element-item" data-filter=".{{ tag.name }}">{{ tag.name }}</button>
		{% endfor %}
	</div>
	<div id="blog" class="row pt-5 grid">

		{% for blog in blogs %}

			{% set tagName = "" %}
			{% for tag in blog.blogHasTag %}
				{% set tagName = tagName ~ ' ' ~ tag.name %}
			{% endfor %}


			<div class="card m-3 col-5 grid-item {{ tagName }}">
				<img class="card-img-top mt-1" src="{{ asset('/assets/img/dechets.jpg') }}" alt="Card image cap">
				<div class="card-body">
					<h5 class="card-title">{{ blog.title }}</h5>
					<p class="card-text">{{ blog.shortContent }}</p>
					<p class="card-text">
						<small class="text-muted">Posté le :
							{{ blog.createdAt ? blog.createdAt|date('Y-m-d') : '' }}</small>
					</p>
					<a href="{{ path('blog_show', {'id': blog.id}) }}" class="btn btn-success">Lire l'article</a>
				</div>
			</div>
		{% else %}

			<tr>
				<td colspan="6">Aucun article trouvé</td>
			</tr>
		{% endfor %}
	</div>

	{% if is_granted('ROLE_ADMIN') %}
	<br>
		<button class="btn btn-primary">
			<a href="{{ path('blog_new') }}">Créer</a>
		</button>
	{% endif %}
{% endblock %}

{% block javascript %}
	<script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.js"></script>
	<script src="{{ asset('/assets/js/scriptsBlog.js') }}"></script>
{% endblock %}

templates/blog/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle entrée{% endblock %}

{% block body %}
    <h1>Ajouter une entrée au Blog</h1>

    {{ include('blog/_form.html.twig') }}

    <a href="{{ path('blog_index') }}">Retour à la liste</a>
{% endblock %}

{% block css %}

<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.16/dist/summernote-bs4.min.css" rel="stylesheet">

{% endblock %}

{% block javascript %}

	<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.16/dist/summernote-bs4.min.js"></script>
	<script>
		$(document).ready(function () {
            $('#summernote').summernote();
        });
    </script>
    
{% endblock %}

templates/blog/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ blog.title }}
{% endblock %}

{% block body %}


	<div id="blog" class="pt-5">
		<h3>{{ blog.title }}</h3>
		<br>
		{{ blog.content|raw }}
		<br>
		{% for tag in blog.blogHasTag %}
			{{tag.name}}
		{% endfor %}
	</div>

	<br>
	<div class="row">
		<button class="btn btn-secondary">
			<a href="{{ path('blog_index') }}">Retour à la liste</a>
		</button>

		{% if is_granted('ROLE_ADMIN') %}
        
			<button class="btn btn-info">
				<a href="{{ path('blog_edit', {'id': blog.id}) }}">Modifier</a>
			</button>

		{{ include('blog/_delete_form.html.twig') }}

		{% endif %}

	</div>
{% endblock %}